# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "nested-stack-without-swagger"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
resolve_s3 = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"



[production]
[production.deploy]
[production.deploy.parameters]
parameter_overrides = """ \
    Environment='prod' \
    HostedZoneId='Z026123931N4UPWWO9QVT' \
    DomainName='api.lab12.cordev.it' \
    CertificateArn='arn:aws:acm:us-east-1:758619197727:certificate/7de5655e-c772-4482-8c3c-2ca9d098bdc8'
"""
stack_name = "nested-stack-without-swagger-prod"
resolve_s3 = true
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []


[develop]
[develop.deploy]
[develop.deploy.parameters]
parameter_overrides = """ \
    Environment='dev' \
    HostedZoneId='Z026123931N4UPWWO9QVT' \
    DomainName='api-dev.lab12.cordev.it' \
    CertificateArn='arn:aws:acm:us-east-1:758619197727:certificate/7de5655e-c772-4482-8c3c-2ca9d098bdc8'
"""
stack_name = "nested-stack-without-swagger-dev"
resolve_s3 = true
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []

[uat]
[uat.deploy]
[uat.deploy.parameters]
parameter_overrides = """ \
    Environment='uat' \
    HostedZoneId='Z026123931N4UPWWO9QVT' \
    DomainName='api-uat.lab12.cordev.it' \
    CertificateArn='arn:aws:acm:us-east-1:758619197727:certificate/7de5655e-c772-4482-8c3c-2ca9d098bdc8'
"""
stack_name = "nested-stack-without-swagger-uat"
resolve_s3 = true
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
