AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for test-nested

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 512

Parameters:
  Var1:
    Type: String
    Default: "test"


Resources:

  ServerlessRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: My API

  
  ServerlessStack1:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./template-nested-1.yaml
      Parameters:
        RestApiId: !Ref ServerlessRestApi 
        RestApiRootResourceId: !GetAtt ServerlessRestApi.RootResourceId

  
  ServerlessStack2:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./template-nested-2.yaml
      Parameters:
        RestApiId: !Ref ServerlessRestApi 
        RestApiRootResourceId: !GetAtt ServerlessRestApi.RootResourceId
         
      
