AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for test-nested

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 512

Parameters:
  RestApiId:
    Type: String
  RestApiRootResourceId:
    Type: String

Resources:


 
# Outputs:
#   TodoPostFunctionArn:
#     Description: "Hello World Lambda Function ARN"
#     Value: !GetAtt TodoPostFunction.Arn
